---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "mimir-mixin.fullname" .) "mimir-rollout-progress" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "mimir-mixin.namespace" . }}
  annotations:
    grafana-folder: {{ .Values.grafana.folder }}
    {{- include "mimir-mixin.annotations" . | indent 4 }}
  labels:
    grafana-dashboard: {{ include "mimir-mixin.name" . }}-mimir-rollout-progress
    {{- include "mimir-mixin.labels" . | indent 4 }}
data:
  mimir-rollout-progress.json: |-
{{ .Files.Get "dashboards/mimir-rollout-progress.json" | indent 4}}