# Copyright (C) 2020 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
name: linkerd-stable-mixin
description: A Helm chart for Linkerd Stable Mixin
home: https://charts.portefaix.xyz
icon:
sources:
  - https://github.com/nlamirault/portefaix-hub/tree/master/charts/linkerd-stable-mixin
kubeVersion: ">= 1.14.0-0"
type: application
keywords:
  - linkerd
  - linkerd-stable
  - monitoring-mixin
  - portefaix

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: stable-2.10.2

maintainers:
  - name: nlamirault
    email: nicolas.lamirault@gmail.com

# https://artifacthub.io/docs/topics/repositories/
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Init chart from Linkerd Stable Mixin
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/links: |
    - name: linkerd
      url: https://linkerd.io
    - name: Portefaix
      url: https://portefaix.xyz
  artifacthub.io/maintainers: |
    - name: nlamirault
      email: nicolas.lamirault@gmail.com
