---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "grafana-mixin.fullname" .) "alerts" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "grafana-mixin.namespace" . }}
  annotations:
{{ include "grafana-mixin.annotations" . | indent 4 }}
{{- if .Values.additionalAnnotations }}
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
  labels:
{{ include "grafana-mixin.labels" . | indent 4 }}
spec:
  groups:
  - name: GrafanaAlerts
    rules:
    - alert: GrafanaRequestsFailing
      annotations:
        message: '''{{`{{`}} $labels.namespace {{`}}`}}'' / ''{{`{{`}} $labels.job {{`}}`}}'' / ''{{`{{`}} $labels.handler {{`}}`}}'' is experiencing {{`{{`}} $value | humanize {{`}}`}}% errors'
      expr: |
        100 * namespace_job_handler_statuscode:http_request_total:rate5m{handler!~"/datasources/proxy/:id.*|/ds/query|/tsdb/query", statuscode=~"5.."}
        /
        namespace_job_handler_statuscode:http_request_total:rate5m{handler!~"/datasources/proxy/:id.*|/ds/query|/tsdb/query"}
        > 0.5
      for: 5m
      labels:
        severity: warning
