---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "grafana-mixin.fullname" .) "rules" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "grafana-mixin.namespace" . }}
  annotations:
{{ include "grafana-mixin.annotations" . | indent 4 }}
{{- if .Values.additionalAnnotations }}
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
  labels:
{{ include "grafana-mixin.labels" . | indent 4 }}
spec:
  groups:
  - name: grafana_rules
    rules:
    - expr: |
        sum by (namespace, job, handler, statuscode) (rate(http_request_total[5m]))
      record: namespace_job_handler_statuscode:http_request_total:rate5m
