repos:
- repo: local
  hooks:
    - id: ct-lint
      name: "Chart Test: Lint"
      language: docker_image
      pass_filenames: false
      types: ['file']
      files: '^charts/.*(\.ya?ml|\.tpl|\.helmignore|NOTES.txt)'
      entry: -u 0 quay.io/helmpack/chart-testing:v3.0.0 ct
      args:
      - lint
    # - id: check-yaml
    #   name: "Check YAML files"        
    # - id: end-of-file-fixer
    # -   id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
