repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      args: [--allow-multiple-documents]
      exclude: ^charts/.*/templates/
    - id: check-added-large-files
- repo: local
  hooks:
    - id: ct-lint
      name: "Chart Test: Lint"
      language: docker_image
      # pass_filenames: false
      types: ['directory']
      files: '^(.git|charts)'
      entry: -u 0 quay.io/helmpack/chart-testing:v3.7.1 ct
      args:
      - lint
      - --validate-maintainers=false
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.11.0
  hooks:
    - id: helm-docs
      args:
        # Make the tool search for charts only under the `example-charts` directory
        - --chart-search-root=charts

        # The `./` makes it relative to the chart-search-root set above
        - --template-files=./_templates.gotmpl

        # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
        # A base filename makes it relative to each chart directory found
        - --template-files=README.md.gotmpl
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
