---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "osm-mixin.fullname" .) "osm-workload-to-workload" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "osm-mixin.namespace" . }}
  annotations:
    grafana-folder: {{ .Values.grafana.folder }}
    {{- include "osm-mixin.annotations" . | indent 4 }}
  labels:
    grafana-dashboard: {{ include "osm-mixin.name" . }}-osm-workload-to-workload
    {{- include "osm-mixin.labels" . | indent 4 }}
data:
  osm-workload-to-workload.json: |-
{{ .Files.Get "dashboards/osm-workload-to-workload.json" | replace "${DS_PROMETHEUS}" "Prometheus" | indent 4}}