{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "prometheus-bbox-exporter.fullname" . }}
  namespace: {{ template "prometheus-bbox-exporter.namespace" . }}
  {{- if .Values.additionalAnnotations }}
  annotations:
  {{ toYaml .Values.additionalAnnotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus-bbox-exporter.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus-bbox-exporter.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "prometheus-bbox-exporter.fullname" . }}
{{- end }}
