{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ template "prometheus-bbox-exporter.namespace" . }}
  {{- if .Values.additionalAnnotations }}
  annotations:
  {{ toYaml .Values.additionalAnnotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus-bbox-exporter.labels" . | indent 4 }}
type: Opaque
data:
  BBOX_EXPORTER_PASSWORD: {{ .Values.exporter.password | b64enc }}
{{- end }}