{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.additionalAnnotations }}
  annotations:
  {{ toYaml .Values.additionalAnnotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus-bbox-exporter.labels" . | indent 4 }}
  name: {{ template "prometheus-bbox-exporter.serviceAccountName" . }}
  namespace: {{ template "prometheus-bbox-exporter.namespace" . }}
{{- end -}}
