{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
{{- if .Values.additionalAnnotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
  labels:
    {{- include "secrets-store-csi-driver-provider-aws.labels" . | indent 4 }}
  name: {{ template "secrets-store-csi-driver-provider-aws.fullname" . }}
  namespace: {{ template "secrets-store-csi-driver-provider-aws.namespace" . }}
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
{{- end }}
