{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
{{- if or .Values.additionalAnnotations .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- if .Values.serviceAccount.annotations }}
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}
  labels:
    app: {{ template "speedtest-exporter.name" . }}
{{- include "speedtest-exporter.labels" . | indent 4 }}
{{- if .Values.serviceMonitor.additionalLabels }}
{{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
{{- end }}
  name: {{ template "speedtest-exporter.fullname" . }}
  namespace: {{ template "speedtest-exporter.namespace" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "speedtest-exporter.name" . }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- if .Values.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
{{- end }}
