---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "thanos-mixin.fullname" .) "rule" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "thanos-mixin.namespace" . }}
  annotations:
    grafana-folder: {{ .Values.grafana.folder }}
{{ include "thanos-mixin.annotations" . | indent 4 }}
  labels:
    grafana-dashboard: {{ include "thanos-mixin.name" . }}-rule
{{ include "thanos-mixin.labels" . | indent 4 }}
data:
  rule.json: |-
{{ .Files.Get "dashboards/rule.json" | indent 4}}