# Default values for portefaix-kyverno.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Provide a name to substitute for the full names of resources
fullnameOverride: ""

# -- Additional labels to add to all resources
customLabels: {}
  # app: portefaix-kubewarden

# -- Additional annotations to add to all resources
customAnnotations: {}

# Kubewarden policies
policies:
  safe_labels: v0.1.7
  safe_annotations: v0.1.1