---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "alertmanager-mixin.fullname" .) "alertmanager-overview" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "alertmanager-mixin.namespace" . }}
  annotations:
    grafana-folder: {{ .Values.grafana.folder }}
{{ include "alertmanager-mixin.annotations" . | indent 4 }}
  labels:
    grafana-dashboard: {{ include "alertmanager-mixin.name" . }}-alertmanager-overview
{{ include "alertmanager-mixin.labels" . | indent 4 }}
data:
  alertmanager-overview.json: |-
{{ .Files.Get "dashboards/alertmanager-overview.json" | indent 4}}