---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "coredns-mixin.fullname" .) "coredns" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "coredns-mixin.namespace" . }}
  annotations:
    grafana-folder: {{ .Values.grafana.folder }}
    {{- include "coredns-mixin.annotations" . | indent 4 }}
  labels:
    grafana-dashboard: {{ include "coredns-mixin.name" . }}-coredns
    {{- include "coredns-mixin.labels" . | indent 4 }}
data:
  coredns.json: |-
{{ .Files.Get "dashboards/coredns.json" | indent 4}}
