---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "promtail-mixin.fullname" .) "promtail" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "promtail-mixin.namespace" . }}
  annotations:
    grafana-folder: {{ .Values.grafana.folder }}
{{ include "promtail-mixin.annotations" . | indent 4 }}
  labels:
    grafana-dashboard: {{ include "promtail-mixin.name" . }}-promtail
{{ include "promtail-mixin.labels" . | indent 4 }}
data:
  promtail.json: |-
{{ .Files.Get "dashboards/promtail.json" | indent 4}}