{{- if .Values.exporter.credentials -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-freebox-exporter.fullname" . }}
  namespace: {{ template "prometheus-freebox-exporter.namespace" . }}
  {{- if .Values.additionalAnnotations }}
  annotations:
  {{ toYaml .Values.additionalAnnotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus-freebox-exporter.labels" . | indent 4 }}
type: Opaque
stringData:
  credentials.json: {{ .Values.exporter.credentials | b64enc | quote }}
{{- end }}
