---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: {{ include "crossplane-aws-factory.name" . }}
  namespace: {{ template "crossplane-aws-factory.namespace" . }}
  labels:
    {{- include "crossplane-aws-factory.labels" . | nindent 4 }}
{{- with .Values.additionalAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    vpcIdRef:
      name: {{ include "crossplane-aws-factory.name" . }}
    tags:
      {{- include "crossplane-aws-factory.awsTags" $ | nindent 6 }}
      - key: Name
        value: {{ include "crossplane-aws-factory.name" . }}
      {{- range $k, $v := .Values.aws.internetgateway.tags }}
      - key: {{ $k }}
        value: {{ $v -}}
      {{ end }}
  writeConnectionSecretToRef:
    name: {{ include "crossplane-aws-factory.name" . }}-igw
    namespace: {{ template "crossplane-aws-factory.namespace" . }}
  providerConfigRef:
    name: {{ include "crossplane-aws-factory.name" . }}
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: {{ include "crossplane-aws-factory.name" . }}
  namespace: {{ template "crossplane-aws-factory.namespace" . }}
  labels:
    {{- include "crossplane-aws-factory.labels" . | nindent 4 }}
{{- with .Values.additionalAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: {{ include "crossplane-aws-factory.name" . }}
    associations:
      - subnetIdRef:
          name: {{ include "crossplane-aws-factory.name" . }}-a
    vpcIdRef:
      name: {{ include "crossplane-aws-factory.name" . }}
    tags: 
      {{- include "crossplane-aws-factory.awsTags" $ | nindent 6 }}
      - key: Name
        value: {{ include "crossplane-aws-factory.name" . }}
      {{- range $k, $v := .Values.aws.routetable.tags }}
      - key: {{ $k }}
        value: {{ $v -}}
      {{ end }}
  writeConnectionSecretToRef:
    name: {{ include "crossplane-aws-factory.name" . }}-route-table
    namespace: {{ template "crossplane-aws-factory.namespace" . }}
  providerConfigRef:
    name: {{ include "crossplane-aws-factory.name" . }}
