---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: {{ include "crossplane-aws-factory.name" . }}
  namespace: {{ template "crossplane-aws-factory.namespace" . }}
  labels:
    {{- include "crossplane-aws-factory.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    tags:
      - key: Name
        value: portefaix-krm-aws
      - key: Service
        value: krm
      - key: Made-by
        value: crossplane
    cidrBlock: {{ .Values.aws.vpc.cidr }}
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
  providerConfigRef:
    name: crossplane-aws
