---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: {{ include "crossplane-gcp-factory.name" . }}
  namespace: {{ template "crossplane-gcp-factory.namespace" . }}
  labels:
    {{- include "crossplane-gcp-factory.labels" . | nindent 4 }}
{{- with .Values.additionalAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  podSecurityContext:
    fsGroup: 2000
  # https://github.com/crossplane/crossplane/blob/master/docs/reference/troubleshoot.md
  args:
    - --debug
  # replicas: 0