{{- if .Values.secret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unifi-poller.fullname" . }}
  namespace: {{ template "unifi-poller.namespace" . }}
  {{- if .Values.additionalAnnotations }}
  annotations:
  {{ toYaml .Values.additionalAnnotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "unifi-poller.labels" . | indent 4 }}
type: Opaque
data:
  up.toml: {{ tpl (toYaml .Values.unifipoller.config) . | b64enc | quote }}
{{- end }}