---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "kubernetes-mixin.fullname" .) "k8s-resources-cluster" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "kubernetes-mixin.namespace" . }}
  annotations:
    grafana-folder: {{ .Values.grafana.folder }}
    {{- include "kubernetes-mixin.annotations" . | indent 4 }}
  labels:
    grafana-dashboard: {{ include "kubernetes-mixin.name" . }}-k8s-resources-cluster
    {{- include "kubernetes-mixin.labels" . | indent 4 }}
data:
  k8s-resources-cluster.json: |-
{{ .Files.Get "dashboards/k8s-resources-cluster.json" | indent 4}}