---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "kubernetes-mixin.fullname" .) "cluster-total" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "kubernetes-mixin.namespace" . }}
  annotations:
    grafana-folder: {{ .Values.grafana.folder }}
    {{- include "kubernetes-mixin.annotations" . | indent 4 }}
  labels:
    grafana-dashboard: {{ include "kubernetes-mixin.name" . }}-cluster-total
    {{- include "kubernetes-mixin.labels" . | indent 4 }}
data:
  cluster-total.json: |-
{{ .Files.Get "dashboards/cluster-total.json" | indent 4}}