---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "fluxcd-mixin.fullname" .) "control-plane" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "fluxcd-mixin.namespace" . }}
  annotations:
{{ include "fluxcd-mixin.annotations" . | indent 4 }}
{{- if .Values.additionalAnnotations }}
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
    grafana-folder: {{ .Values.grafana.folder }}
  labels:
{{ include "fluxcd-mixin.labels" . | indent 4 }}
    grafana-dashboard: {{ include "fluxcd-mixin.name" . }}-control-plane
data:
  control-plane.json: |-
{{ .Files.Get "dashboards/control-plane.json" | indent 4}}