---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "fluxcd-mixin.fullname" .) "cluster" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "fluxcd-mixin.namespace" . }}
  annotations:
    grafana-folder: {{ .Values.grafana.folder }}
    {{- include "fluxcd-mixin.annotations" . | indent 4 }}
  labels:
    grafana-dashboard: {{ include "fluxcd-mixin.name" . }}-cluster
    {{- include "fluxcd-mixin.labels" . | indent 4 }}
data:
  cluster.json: |-
{{ .Files.Get "dashboards/cluster.json" | indent 4}}