# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Charts / Validate

on:
  push:
    branches:
      - master
    paths:
      - "charts/**"
  pull_request:
    branches:
      - master
    # paths:
    #   - "charts/**"

jobs:
  # kubeval:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Validate
  #       uses: desaintmartin/helm-kubeval-action@v1.1.0
  #       with:
  #         path: ./charts
  #         config: ./.github/config_repos

  # kubeconform:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: login to Github Packages
  #       run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Validate
  #       uses: docker://ghcr.io/yannh/kubeconform:master
  #       with:
  #         entrypoint: '/kubeconform'
  #         args: "-summary -verbose -summary -schema-location default ./charts"

  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate
        uses: nlamirault/helm-kubeconform-action@master
        with:
          charts: ./charts